[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TriTan"
authors = [{name = "maxxxxxxxin", email = "xin.ma-2@postgrad.manchester.ac.uk"}]
dynamic = ["version", "description"]
